# Assignment 1

## Question 1: Softmax

In [1]:
import numpy as np

In [10]:
def softmax(x):
    """Compute the softmax function for each row of the input x.

    It is crucial that this function is optimized for speed because
    it will be used frequently in later code. You might find numpy
    functions np.exp, np.sum, np.reshape, np.max, and numpy
    broadcasting useful for this task.

    Numpy broadcasting documentation:
    http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

    You should also make sure that your code works for a single
    D-dimensional vector (treat the vector as a single row) and
    for N x D matrices. This may be useful for testing later. Also,
    make sure that the dimensions of the output match the input.

    You must implement the optimization in problem 1(a) of the
    written assignment!

    Arguments:
    x -- A D dimensional vector or N x D dimensional numpy matrix.

    Return:
    x -- You are allowed to modify x in-place
    """
    orig_shape = x.shape

    if len(x.shape) > 1:
        # Matrix
        ### YOUR CODE HERE
        normalized_x = x - np.amax(x, axis=1)[:, np.newaxis]
        exp_x = np.exp(normalized_x)
        s_sum_rows = np.sum(exp_x, axis=1)
        x = np.divide(exp_x, s_sum_rows)
        #raise NotImplementedError
        ### END YOUR CODE
    else:
        # Vector
        ### YOUR CODE HERE
        normalized_x = x - np.max(x)
        exp_x = np.exp(normalized_x)
        x = exp_x / np.sum(exp_x)
        #raise NotImplementedError
        ### END YOUR CODE

    assert x.shape == orig_shape
    return x


In [14]:
def test_softmax_basic():
    """
    Some simple tests to get you started.
    Warning: these are not exhaustive.
    """
    print ("Running basic tests...")
    test1 = softmax(np.array([1,2]))
    print (test1)
    ans1 = np.array([0.26894142,  0.73105858])
    assert np.allclose(test1, ans1, rtol=1e-05, atol=1e-06)

    test2 = softmax(np.array([[1001,1002],[3,4]]))
    print (test2)
    ans2 = np.array([
        [0.26894142, 0.73105858],
        [0.26894142, 0.73105858]])
    assert np.allclose(test2, ans2, rtol=1e-05, atol=1e-06)

    test3 = softmax(np.array([[-1001,-1002]]))
    print (test3)
    ans3 = np.array([[0.73105858, 0.26894142]])
    assert np.allclose(test3, ans3, rtol=1e-05, atol=1e-06)

    print ("You should be able to verify these results by hand!\n")


In [15]:
def test_softmax():
    """
    Use this space to test your softmax implementation by running:
        python q1_softmax.py
    This function will not be called by the autograder, nor will
    your tests be graded.
    """
    print ("Running your tests...")
    ### YOUR CODE HERE
    raise NotImplementedError
    ### END YOUR CODE

In [17]:
test_softmax_basic()
#test_softmax()

Running basic tests...
[0.26894142 0.73105858]
[[0.26894142 0.73105858]
 [0.26894142 0.73105858]]
[[0.73105858 0.26894142]]
You should be able to verify these results by hand!



----------------------

In [18]:
softmax(np.array([[1,1],[1,1]]))

array([[0.5, 0.5],
       [0.5, 0.5]])

In [19]:
test1 = softmax(np.array([1,2]))

In [20]:
ans1 = np.array([0.26894142,  0.73105858])
assert np.allclose(test1, ans1, rtol=1e-05, atol=1e-06) 

### Test 2

In [36]:
test2 = softmax(np.array([[1001,1002],[3,4]]))
print (test2)
ans2 = np.array([
        [0.26894142, 0.73105858],
        [0.26894142, 0.73105858]])
assert np.allclose(test2, ans2, rtol=1e-05, atol=1e-06)


[[0.5 0.5]
 [0.5 0.5]]


AssertionError: 

In [37]:
x = np.array([[1001,1002],[3,4]])

In [38]:
np.amax(x, axis=1)

array([1002,    4])

In [39]:
normalized_x = x - np.amax(x, axis=1)[:, np.newaxis]
normalized_x

array([[-1,  0],
       [-1,  0]])

In [41]:
exp_x = np.exp(normalized_x)
exp_x

array([[0.36787944, 1.        ],
       [0.36787944, 1.        ]])

In [43]:
s_sum_rows = np.sum(exp_x, axis=1)[:, np.newaxis]
s_sum_rows

array([[1.36787944],
       [1.36787944]])

In [44]:
x = np.divide(exp_x, s_sum_rows)
x

array([[0.26894142, 0.73105858],
       [0.26894142, 0.73105858]])

### Test 3

In [50]:
x = np.array([[-1001,-1002]])

In [64]:
x.shape

(1, 2)

In [51]:
np.amax(x, axis=1)

array([-1001])

In [52]:
normalized_x = x - np.amax(x, axis=1)[:, np.newaxis]
normalized_x

array([[ 0, -1]])

In [53]:
exp_x = np.exp(normalized_x)
exp_x

array([[1.        , 0.36787944]])

In [54]:
s_sum_rows = np.sum(exp_x, axis=1)[:, np.newaxis]
s_sum_rows

array([[1.36787944]])

In [55]:
x = np.divide(exp_x, s_sum_rows)
x

array([[0.73105858, 0.26894142]])

## Question 2: Sigmoid

### e) Sigmoid


In [21]:
def sigmoid(x):
    """
    Compute the sigmoid function for the input here.

    Arguments:
    x -- A scalar or numpy array.

    Return:
    s -- sigmoid(x)
    """

    ### YOUR CODE HERE
    s = 1/(1+np.exp(-x))
    #raise NotImplementedError
    ### END YOUR CODE

    return s

In [22]:
def sigmoid_grad(s):
    """
    Compute the gradient for the sigmoid function here. Note that
    for this implementation, the input s should be the sigmoid
    function value of your original input x.

    Arguments:
    s -- A scalar or numpy array.

    Return:
    ds -- Your computed gradient.
    """

    ### YOUR CODE HERE
    ds = s*(1-s)
    #raise NotImplementedError
    ### END YOUR CODE

    return ds

In [23]:
def test_sigmoid_basic():
    """
    Some simple tests to get you started.
    Warning: these are not exhaustive.
    """
    print ("Running basic tests...")
    x = np.array([[1, 2], [-1, -2]])
    f = sigmoid(x)
    g = sigmoid_grad(f)
    print (f)
    f_ans = np.array([
        [0.73105858, 0.88079708],
        [0.26894142, 0.11920292]])
    assert np.allclose(f, f_ans, rtol=1e-05, atol=1e-06)
    print (g)
    g_ans = np.array([
        [0.19661193, 0.10499359],
        [0.19661193, 0.10499359]])
    assert np.allclose(g, g_ans, rtol=1e-05, atol=1e-06)
    print ("You should verify these results by hand!\n")

In [24]:
x = np.array([[1, 2], [-1, -2]])
f = sigmoid(x)
g = sigmoid_grad(f)

In [25]:
f

array([[0.73105858, 0.88079708],
       [0.26894142, 0.11920292]])

In [26]:
g

array([[0.19661193, 0.10499359],
       [0.19661193, 0.10499359]])

### f) Gradient checking


In [31]:
import random

In [35]:
# First implement a gradient checker by filling in the following functions
def gradcheck_naive(f, x):
    """ Gradient check for a function f.

    Arguments:
    f -- a function that takes a single argument and outputs the
         cost and its gradients
    x -- the point (numpy array) to check the gradient at
    """

    rndstate = random.getstate()
    random.setstate(rndstate)
    fx, grad = f(x) # Evaluate function value at original point
    h = 1e-4        # Do not change this!

    # Iterate over all indexes ix in x to check the gradient.
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        ix = it.multi_index

        # Try modifying x[ix] with h defined above to compute numerical
        # gradients (numgrad).

        # Use the centered difference of the gradient.
        # It has smaller asymptotic error than forward / backward difference
        # methods. If you are curious, check out here:
        # https://math.stackexchange.com/questions/2326181/when-to-use-forward-or-central-difference-approximations

        # Make sure you call random.setstate(rndstate)
        # before calling f(x) each time. This will make it possible
        # to test cost functions with built in randomness later.

        ### YOUR CODE HERE:
        random.setstate(rndstate)
        print(x[ix])
        print(f(x[ix]+h)[0])
        numgrad = (f(x[ix]+h)[0] - f(x[ix]-h)[0] )/(2*h)
        #raise NotImplementedError
        ### END YOUR CODE

        # Compare gradients
        reldiff = abs(numgrad - grad[ix]) / max(1, abs(numgrad), abs(grad[ix]))
        if reldiff > 1e-5:
            print ("Gradient check failed.")
            print ("First gradient error found at index %s" % str(ix))
            print ("Your gradient: %f \t Numerical gradient: %f" % (
                grad[ix], numgrad))
            return

        it.iternext() # Step to next dimension

    print ("Gradient check passed!")

In [36]:
def sanity_check():
    """
    Some basic sanity checks.
    """
    quad = lambda x: (np.sum(x ** 2), x * 2)

    print ("Running sanity checks...")
    gradcheck_naive(quad, np.array(123.456))      # scalar test
    gradcheck_naive(quad, np.random.randn(3,))    # 1-D test
    gradcheck_naive(quad, np.random.randn(4,5))   # 2-D test
    print ("")

In [37]:
sanity_check()

Running sanity checks...
123.456
15241.408627210001
Gradient check passed!
0.04334956728117089
0.0018878648969209962
-0.11844931847098084
0.014006561182545644
1.0744171615015292
1.1545871303613033
Gradient check passed!
-0.04045765541269687
0.0016287403504099808
-0.0021913495497996567
4.373742939447228e-06
-0.32265012535306187
0.10403858336527592
-1.3505705728304993
1.823770768081137
0.21421606802116638
0.045931377012053215
0.41218982363120255
0.1699828986698481
0.40778041839761975
0.16636643571221732
-0.5902934845373058
0.34832834919028705
1.0406901834028952
1.0832442058678322
-0.061901704323229834
0.003819450657255925
0.5932788507941136
0.35209846056974287
-0.0008969824891892556
6.351810880743018e-07
1.705245345178542
2.9082027463221207
1.340121347371271
1.796193259949665
0.20923998971170965
0.043823231292498696
0.7343655741382952
0.5394396795942955
-0.20766982569218936
0.04308523253788588
0.4686489568923897
0.21972558458770342
1.7517321909049002
3.0689160250906626
0.181017366057713
