# CS224n

# Assignment 2

---

## Tensorflow Softmax

### (a)

In [1]:
import numpy as np
import tensorflow as tf
from utils.general_utils import test_all_close

In [41]:
print(tf.__version__)

1.13.1


In [2]:
tf.enable_eager_execution()

In [46]:
x = tf.constant([[1,2,3],[4,5,6]], dtype=tf.float64)

In [47]:
print(x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [48]:
x_max = tf.reduce_max(x, axis=0)
x2 = x - x_max

In [49]:
print(x_max)

tf.Tensor([4. 5. 6.], shape=(3,), dtype=float64)


In [50]:
print(x2)
print("shape: ", x2.shape)

tf.Tensor(
[[-3. -3. -3.]
 [ 0.  0.  0.]], shape=(2, 3), dtype=float64)
shape:  (2, 3)


In [51]:
exp_x2 = tf.exp(x2)

In [52]:
print(exp_x2)
print("shape: ", exp_x2.shape)

tf.Tensor(
[[0.04978707 0.04978707 0.04978707]
 [1.         1.         1.        ]], shape=(2, 3), dtype=float64)
shape:  (2, 3)


In [56]:
denum = tf.reduce_sum(exp_x2, axis= 0, keep_dims=True)
print(denum)

tf.Tensor([[1.04978707 1.04978707 1.04978707]], shape=(1, 3), dtype=float64)


In [57]:
exp_x2 / denum

<tf.Tensor: id=70, shape=(2, 3), dtype=float64, numpy=
array([[0.04742587, 0.04742587, 0.04742587],
       [0.95257413, 0.95257413, 0.95257413]])>